name: Bug report
description: Create a report to help us improve
labels: [bug]
title: "bug: <short>"
body:
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior
    validations:
      required: true
  - type: input
    id: repro
    attributes:
      label: Reproduction steps
  - type: input
    id: version
    attributes:
      label: Version/commit
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
